Добавлена возможность десериализации json из строки для json полей.
Flexberry/Flexberry.JavaODataBackendGIS.Sample pull request #21
Opened 2023-02-14 14:41 UTC by VChurekov

2023-02-14 16:04 UTC, TeterinaSvetlana approved these changes

2023-02-15 07:14 UTC, VChurekov commented
Заметил что в Flexberry.GIS/service/MutableHttpFilter.java методы на модификацию ответа сервера работают как-то странно, применяется только первый вызванный метод. Даже ранее из двух строк применялась только первая, которая на счет primaryKey
mutableResponse.replaceSubstringInResponse("Primarykey", "__PrimaryKey");
mutableResponse.replaceSubstringInResponse(" eq ", "+eq+");
Вторая строка не имела эффекта...
Добавил методы InitOriginalContent и SetupOrdinalContent чтобы все исправления записались респонс один раз, после того как все методы отработали. Методы теперь не дергают респонс, а работают с внутренней переменной.
С ошибкой подробно не разбирался, но скорее всего такое поведение вызвано тем что после первой записи правок, туда более нельзя внести изменения.

2023-02-15 08:51 UTC, AntonIV8 requested changes

2023-02-15 08:51 UTC, AntonIV8 commented on JavaGISOdataBackend/src/main/java/Flexberry.GIS/service/MutableHttpFilter.java
> +        mutableResponse.SetupOrdinalContent();
Тут наверное опечатка (Original)

2023-02-15 08:59 UTC, VChurekov commented on JavaGISOdataBackend/src/main/java/Flexberry.GIS/service/MutableHttpFilter.java
> +        mutableResponse.SetupOrdinalContent();
Поправил.

2023-02-15 09:50 UTC, AntonIV8 requested changes

2023-02-15 09:50 UTC, AntonIV8 commented on JavaGISOdataBackend/src/main/java/Flexberry.GIS/service/MutableHttpResponse.java
> +    public void InitOriginalContent() throws IOException {
Может переименовать во что-то типа CacheOriginalContent ?

2023-02-15 09:50 UTC, AntonIV8 commented on JavaGISOdataBackend/src/main/java/Flexberry.GIS/service/MutableHttpResponse.java
> +    public void SetupOriginalContent() throws IOException {
Тут опечатка. Но я бы назвал метод ApplyChangesForResponse

2023-02-15 09:55 UTC, VChurekov commented on JavaGISOdataBackend/src/main/java/Flexberry.GIS/service/MutableHttpResponse.java
> +    public void InitOriginalContent() throws IOException {
Переименовал.

2023-02-15 09:55 UTC, VChurekov commented on JavaGISOdataBackend/src/main/java/Flexberry.GIS/service/MutableHttpResponse.java
> +    public void SetupOriginalContent() throws IOException {
Переименовал.

2023-02-20 05:26 UTC, AntonIV8 approved these changes

2023-02-20 05:26 UTC, merged